spring.application.name=spring-api
spring.datasource.url=jdbc:postgresql://localhost:5432/CWWforms
spring.datasource.username=portgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
